### ISSUE TITLE
SEPA Import fail - Cannot convert from "US-ASCII//TRANSLIT" to "UTF-8

### ISSUE THREAD

**Issue by ds2k5** [cstim/aqbanking#1]
Hello,
using FreeBSD 11.1 ( aqbanking-5.7.8, GNUCash 2.6.19 build from port )
wanna Import SEPA beause GNUCASH is fail.

Actions -> Online Actions -> Issue SEPA Transaction

https://www.pic-upload.de/view-34860393/gnucash_sepa.png.html

```

% aqhbci-tool4 getaccsepa -b 111111111 -a 2222222222
3:2018/02/17 16-29-14:gwen(3798):gui.c:  179: Cannot convert from "US-ASCII//TRANSLIT" to "UTF-8", Invalid argument
3:2018/02/17 16-29-14:gwen(3798):args.c:   71: Error parsing "-b"
ERROR: Could not parse arguments

```

What did I wrong ?
Thanks

**Comment by cstim** [comment]
Unfortunately the issue list here is not used at all. Please go to https://www.aquamaniac.de/rdm/projects/aqbanking
